spring:
  application:
    name: spring-boot-app

server.port: 8081


#tag::datasource[]
spring.datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
#end::datasource[]
